---
- hosts: all
  remote_user: logging_user
  become: yes
  become_method: sudo
  become_user: root

  vars:
    ansible_become_pass: 'sudo_passwd'
    password: passwd

  tasks:
    - name: Add user 'name' with docker group
      user:
        name: name
        comment: awesome
        shell: /bin/bash
        groups: docker
        append: yes
        update_password: always
        password: "{{ password | password_hash('sha512') }}"
